<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<IsPackable>false</IsPackable>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<OutputType>WinExe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\WindowsFormsLifetime\WindowsFormsLifetime.csproj" />
		<ProjectReference Include="..\..\src\WindowsFormsLifetime.Analyzers\WindowsFormsLifetime.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
		<ProjectReference Include="..\..\src\WindowsFormsLifetime.CodeFixes\WindowsFormsLifetime.CodeFixes.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
	</ItemGroup>

</Project>