using System;
using System.IO;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace WindowsFormsLifetime.Analyzers;

internal static class GeneratedCode
{
    internal static bool IsGenerated(SyntaxTree tree, CancellationToken cancellationToken)
    {
        string fileName = Path.GetFileName(tree.FilePath);
        if (fileName.StartsWith("TemporaryGeneratedFile_", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        foreach (SyntaxTrivia trivia in tree.GetRoot(cancellationToken).GetLeadingTrivia())
        {
            if ((trivia.IsKind(SyntaxKind.SingleLineCommentTrivia)
                    || trivia.IsKind(SyntaxKind.MultiLineCommentTrivia))
                && (trivia.ToString().IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0
                    || trivia.ToString().IndexOf("<autogenerated", StringComparison.OrdinalIgnoreCase) >= 0))
            {
                return true;
            }
        }

        return false;
    }

    internal static bool IsGenerated(ISymbol symbol, Compilation compilation)
    {
        INamedTypeSymbol? generatedCode = compilation.GetTypeByMetadataName("System.CodeDom.Compiler.GeneratedCodeAttribute");
        INamedTypeSymbol? compilerGenerated = compilation.GetTypeByMetadataName("System.Runtime.CompilerServices.CompilerGeneratedAttribute");
        return IsGenerated(symbol, generatedCode, compilerGenerated);
    }

    internal static bool IsGenerated(ISymbol symbol, INamedTypeSymbol? generatedCode, INamedTypeSymbol? compilerGenerated)
    {
        for (ISymbol? current = symbol; current != null; current = current.ContainingSymbol)
        {
            foreach (AttributeData attribute in current.GetAttributes())
            {
                if (attribute.AttributeClass != null
                    && (SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, generatedCode)
                        || SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, compilerGenerated)))
                {
                    return true;
                }
            }
        }

        return false;
    }
}
